### ISSUE TITLE
issue on streamnetwork.py

### ISSUE THREAD

**Issue by jeanka1991** [pnnl/DHSVM-PNNL#21]
Hello,
This line fails without previous statistics calculation:

https://github.com/pnnl/DHSVM-PNNL/blob/3830b82fd5efed927e1cd09ababe46e390082d56/CreateStreamNetwork_PythonV/createstreamnetwork.py#L192

I added "arcpy.CalculateStatistics_management(elevras)" between the lines 191 and 192

But if the code is working as it is uploaded I must have done some mistake,

jeancarlos

**Comment by zrduan** [comment]
Hello,

What you did looks correct to me!  In most cases, the raster comes with some basic stats(max, min, mean etc.) in its properties that's why the line you added was not a default in the script. But for DEM raster that does not come with those stats, an extra command line would be needed to calculate stats as you did or ArcGIS can be used to pre-process the DEM before running the script.  Hope this helps. 

Zhuoran
